try{
    anotherFunction()
} catch{
    console.log("Error");
}   

try {
    hello()
} catch(e) {
    console.log('F por el hello()!')
    console.log(e);
}